name = "STSP"
uuid = "a1a05d49-eb2b-43ca-b285-11501fa99875"
author = ["Maxence Gollier <maxence-2.gollier@polymtl.ca> and Sacha Benarroch-Lelong <sacha.benarroch@polymtl.ca>"]
version = "1.0.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
