name = "STSP"
uuid = "a1a05d49-eb2b-43ca-b285-11501fa99875"
author = ["Maxence Gollier <maxence-2.gollier@polymtl.ca> and Sacha Benarroch-Lelong <sacha.benarroch@polymtl.ca>"]
version = "1.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Documenter = "1.7.0"
DocumenterTools = "0.1.20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
